version: 1.0.{build}

image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python38"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt"

build: off

test_script:
  - cmd: "%PYTHON%\\python.exe --version"
  - cmd: "%PYTHON%\\python.exe -c \"print('Build successful')\""